---
## Add any additional packages
additional_packages:
  - nfs-utils
  - iscsi-initiator-utils
  - device-mapper-multipath
  - sg3_utils
  - git
  - https://s3.{{ region| default("eu-west-2") }}.amazonaws.com/amazon-ssm-{{ region| default("eu-west-2") }}/latest/linux_amd64/amazon-ssm-agent.rpm
  - libselinux-python
  - libsemanage-python
  - screen
  - logrotate

pip_install_packages:
  - name: pip
    state: latest
  - name: ansible
    version: "2.10.6"
  - name: j2cli
    umask: "0022"

selinux_policies:
  - antivirus_can_scan_system
  - nagios_run_sudo

## CloudWatch Agent Variables
cwa_conf_json_file_content: "{{ lookup('file', 'files/cloudwatch-config.json') }}"

## CIS Hardening Variables
rhel8cis_time_synchronization: chrony
rhel8cis_time_synchronization_servers: ["169.254.169.123"] #Default VPC source
rhel8cis_squid_server: true
rhel8cis_firewall: "iptables"
#Disable rsyslog/syslog-ng, using cloudwatch
rhel8cis_rule_4_2_3: false
rhel8cis_rule_4_2_1_1: false
rhel8cis_rule_4_2_1_2: false
rhel8cis_rule_4_2_1_3: false
rhel8cis_rule_4_2_1_4: false
rhel8cis_rule_4_2_1_5: false
rhel8cis_rule_4_2_2_1: false
rhel8cis_rule_4_2_2_2: false
rhel8cis_rule_4_2_2_3: false
rhel8cis_rule_4_2_2_4: false
rhel8cis_rule_4_2_2_5: false
rhel8cis_rule_4_3: false
#Disable GRUB tasks
rhel8cis_rule_1_4_2: false
rhel8cis_rule_1_6_1_1: false
rhel8cis_rule_4_1_3: false
#Disable Firewall Tasks, we manage this in app deploy
rhel8cis_rule_3_6_1: false
rhel8cis_rule_3_6_2: false
rhel8cis_rule_3_6_3: false
rhel8cis_rule_3_6_4: false
rhel8cis_rule_3_6_5: false
rhel8cis_rule_5_4_4: false
# Setup hosts.allow entries
rhel8cis_host_allow:
  - "127.0.0.1"
  - "10.0.0.0/255.0.0.0"
  - "172.16.0.0/255.240.0.0"
  - "192.168.0.0/255.255.0.0"

## Nagios agent variables
nagios_host: nagios.sharedservices.aws.internal
nrpe_allowed_hosts:
  - "127.0.0.1"
  - "10.44.12.0/24"
  - "10.44.13.0/24"	
  - "10.44.14.0/24"
nrpe_command:
  check_disk_all:
    script: check_disk
    option: -w 80 -c 90
nrpe_config: 
  dont_blame_nrpe: 1