---
- hosts: rhel8-base
  become: true
  collections:
    - ch_collections.base
  pre_tasks:
    - name: CodeReady repo check
      block:
        - name: Check CodeReady repo exists
          ansible.builtin.stat:
            path: /etc/yum.repos.d/redhat-rhui.repo
          register: repo
        - name: Enable CodeReady repo on RHEL8 only
          ini_file: 
            dest: /etc/yum.repos.d/redhat-rhui.repo
            section: codeready-builder-for-rhel-8-rhui-rpms
            option: enabled
            value: 1
          when: repo.stat.exists
      when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int == 8)
    - name: Enable AWS SSM GPG
      block:
        - name: Copy GPG key
          copy:
            src: amazon-ssm-agent.gpg
            dest: /tmp/amazon-ssm-agent.gpg
            owner: root
            group: root
            mode: '0644'
        - name: Import GPG key
          ansible.builtin.rpm_key:
            key: /tmp/amazon-ssm-agent.gpg
            state: present
        - name: Verify the key, using a fingerprint, before import
          ansible.builtin.rpm_key:
            key: /tmp/amazon-ssm-agent.gpg
            fingerprint: 8108 A07A 9EBE 248E 3F1C  63F2 54F4 F56E 693E CA21
            validate_certs: no
      
    - name: Updating System Packages Before Ansible Run
      package:
        name: '*'
        state: latest
    - name: Set timezone to Europe/London
      community.general.timezone:
        name: Europe/London
  roles:
    - epel
    - ch_collections.base.pip
    - ch_collections.base.os_package_control
    - RHEL8-CIS
    - cloudwatch-agent
    - ch_collections.base.cloudwatch_agent_helper
    - ch_collections.base.nagios_nrpe_client
    - clamav
  tasks: 
    - name: update iscsi config setting
      lineinfile: 
        path: /etc/iscsi/iscsid.conf
        regexp: '^node.session.timeo.replacement_timeout = 120' 
        line: 'node.session.timeo.replacement_timeout = 5'
        backrefs: yes
    - name: Run multipath config tool to enable multipath and disable user friendly names
      command: mpathconf --enable --with_multipathd y --user_friendly_names n
      args:
        creates: /etc/multipath.conf
    - name: update mpath config to disable friendly names
      lineinfile: 
        path: /etc/multipath.conf
        insertafter: '^defaults*'
        line: 'user_friendly_names no'
    - name: Make sure aws ssm agent is enabled
      service:
        name: amazon-ssm-agent
        state: stopped
        enabled: yes
    - name: Create persistent SELinux boolean policies
      ansible.posix.seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop: "{{ selinux_policies }}"