---
collections:
  - name: https://github.com/companieshouse/ansible-collections.git#ch_collections/base
    version: 0.1.128
    type: git
  - name: community.general
    version: 4.8.0
  - name: ansible.posix
    version: 1.1.1
  - name: https://github.com/companieshouse/ansible-collections.git#ch_collections/security_banner
    type: git

roles:
  - name: geerlingguy.repo-epel
  - src: https://github.com/ansible-lockdown/RHEL8-CIS.git
    name: RHEL8-CIS
    version: 1.4.0
  - src: https://github.com/christiangda/ansible-role-amazon-cloudwatch-agent.git
    name: cloudwatch-agent
