---
collections:
  - name: https://github.com/companieshouse/ansible-collections.git#ch_collections/base
    version: 0.1.86
    type: git
  - name: ansible.posix
    version: 1.1.1

roles:
  - src: https://github.com/geerlingguy/ansible-role-repo-epel
    name: epel
    # version: "1.3.0"
  - src: https://github.com/ansible-lockdown/RHEL8-CIS.git
    name: RHEL8-CIS
    # version: "ce603b0e676fedbf6e79ae89187c87b7a98a2c23"
  - src: https://github.com/companieshouse/ansible-role-amazon-cloudwatch-agent.git
    name: cloudwatch-agent