---
collections:
  - name: https://github.com/companieshouse/ansible-collections.git#ch_collections/base
    version: 0.1.89
    type: git
  - name: ansible.posix
    version: 1.1.1

roles:
  - name: geerlingguy.repo-epel
    # version: "1.3.0"
  - src: https://github.com/ansible-lockdown/RHEL8-CIS.git
    name: RHEL8-CIS
    version: "1.4.0"
  - src: https://github.com/christiangda/ansible-role-amazon-cloudwatch-agent.git
    name: cloudwatch-agent